[package]
name = "rust_markdown_parser"
version = "0.1.0"
edition = "2021"
description = "Simplified markdown parser implemented in Rust."

[dependencies]
pest = "2.7.14"
pest_derive = "2.7.14"
anyhow = "1.0.93"
thiserror = "2.0.3"